stages:
  - build
  - deploy

build_image:
  stage: build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - docker pull node:alpine
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.sebbo.net
    - docker build -t docker.sebbo.net/sebbo2002/plex-notifications:$CI_COMMIT_REF_NAME .
    - docker push docker.sebbo.net/sebbo2002/plex-notifications:$CI_COMMIT_REF_NAME
    - docker tag docker.sebbo.net/sebbo2002/plex-notifications:$CI_COMMIT_REF_NAME docker.sebbo.net/sebbo2002/plex-notifications
    - docker push docker.sebbo.net/sebbo2002/plex-notifications
  only:
    - tags

check:
  stage: build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - npm ci
    - npm run check
  except:
    - tags

publish_github:
  stage: build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - git pull
    - git push --force "https://${GITHUB_AUTH}@github.com/sebbo2002/plex-notifications.git" --all
  except:
    - tags

publish_github_tags:
  stage: build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - git push --force "https://${GITHUB_AUTH}@github.com/sebbo2002/plex-notifications.git" --tags

deployment:
  stage: deploy
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - docker login -u "gitlab-ci-token" -p "${CI_BUILD_TOKEN}" docker.sebbo.net
    - docker pull docker.sebbo.net/sebbo2002/plex-notifications
    - docker stop "plex-notifications" || true
    - docker rm "plex-notifications" || true
    - docker create --restart "always" --name="plex-notifications"
        -p 127.0.0.1:10032:8888
        -e PUSHOVER_USER="${PUSHOVER_USER}"
        -e PUSHOVER_TOKEN="${PUSHOVER_TOKEN}"
        docker.sebbo.net/sebbo2002/plex-notifications
    - docker start plex-notifications
  only:
    - master

trigger_dockerhub:
  stage: deploy
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - curl -X "POST" "https://registry.hub.docker.com/u/sebbo2002/plex-notifications/trigger/59ff1b8a-54f6-4e23-9847-c79ad25ba7f3/"
  only:
    - tags
