stages:
  - build

build_image:
  stage: build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.sebbo.net
    - docker build -t docker.sebbo.net/sebbo2002/docker-plex-notifications .
    - docker push docker.sebbo.net/sebbo2002/docker-plex-notifications
  only:
    - master